apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: {{ .Values.hello.replicas }}
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: random-logger
        image: chentex/random-logger:{{ .Values.hello.version }}
        volumeMounts:
        - name: hellopython
          mountPath: /var/log
      volumes:
      - name: hellopython
        hostPath:
           path: /var/log
